### ISSUE TITLE
Create react boilerplate 

### ISSUE THREAD

**Issue by indraasura** [indraasura/Rahat#1]

**Comment by yashgoyal2802** [comment]
on it

**Comment by yashgoyal2802** [comment]
solved the issue, pls have a look

**Comment by indraasura** [comment]
> solved the issue, pls have a look

The file was still there when I merged it. From now on, whenever there are multiple commits in one PR, either do the following:

1. Squash commits 
or 
2. Delete existing PR and issue new one

Also, please mention the issue which is being fixed so that the issue closes automatically when I merge PR by either writing Fixes #issue_number or Fixed #issue_number

**Comment by yashgoyal2802** [comment]
so, should i make a new PR again?

**Comment by indraasura** [comment]
> so, should i make a new PR again?

You can either squash it or make new pr, as it is written above

**Comment by indraasura** [comment]
@yashgoyal2802 how many more days to create a basic boilerplate?

**Comment by yashgoyal2802** [comment]
Already done

**Comment by yashgoyal2802** [comment]
I am having issue in making a new PR, it's not creating a new PR as there are no chages in file

**Comment by indraasura** [comment]
I just checked your fork, it still has the package-lock.json file. 
Add that to .gitignore, push, issue PR 
I'll wait till 12:00 today, else, I am doing it

**Comment by yashgoyal2802** [comment]
done.
